name: mockshop
description: A Shop App made with flutter for a test.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-122.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  container_tab_indicator: ^0.3.0
  flutter_launcher_icons: ^0.11.0
  animated_splash_screen: ^1.3.0
  lottie: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/images/icon_apk.png"
  adaptive_icon_background: "#FFFFFF"
  icon_size: 50

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
