// ignore_for_file: prefer_const_constructors

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../../Services/products_controller.dart';

class HomePage extends GetView<ProductsController> {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Mock Shop'),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            // ignore: prefer_const_literals_to_create_immutables
            children: [
              Text('TESTE'),
              Text('TESTE'),
              Text('-----------------------------------'),
              Text('-----------------------------------'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
              Text('TESTE'),
            ],
          ),
        ),
      ),
    );
  }
}
